python mainBSPF.py \
  --ae \
  --phase 1 \
  --sample_dir samples/bsp_ae_out \
  --start 0 \
  --end 9000 \
  --data_dir ../NTMorph/data/all_vox256_img/ \
  --train \
  --iteration 16000000 \
  --learning_rate 0.001 \
  --dataset_partition train \
  --bspf_name "shiftrestrict_negsrc2" \
  --use_wandb
